### PR TITLE
Fix non connected graph rendering errors

### LINKED ISSUE #1407: Quasar support - graph rendering is broken
likely due to graph being only 2 non connected elements

### PR DESCRIPTION
**Pull request by aidemsined**
Avoid updating state during render by moving the fallback logic that sets currentOperationId into a useEffect. Add guards for empty connectedNodeIds and undefined fallback values, and use a safe fallback for focusNodeId (using ??). The effect only calls setCurrentOperationId when a valid, different fallback id exists, preventing render-time state updates and related React warnings.

closes #1407

### CODE REVIEW

File: src/components/OperationGraphComponent.tsx [hunk 1]
```diff
@@ -80,13 +80,22 @@ const OperationGraph: React.FC<{
...
-        setCurrentOperationId(val);
+    if (currentOperationId !== null && connectedNodeIds.size > 0 && !connectedNodeIds.has(currentOperationId)) {
+        focusNodeId = connectedNodeIds.values().next().value ?? focusNodeId;
     }
 
+    useEffect(() => {
+        if (connectedNodeIds.size === 0) {
+            return;
+        }
+        if (currentOperationId !== null && !connectedNodeIds.has(currentOperationId)) {
```
Comment (dcblundell) [inline src/components/OperationGraphComponent.tsx:91]: Maybe combine these conditions so we return early if there are not `connectedNodeIds` or `currentOperationId`.

**Review by dcblundell — APPROVED** [review]

File: src/components/OperationGraphComponent.tsx (hunk 1 above)
Comment (aidemsined) [reply src/components/OperationGraphComponent.tsx:91]: i think its easier to read separated
