### PR TITLE
Fix/Conflicting peer dependency

### LINKED ISSUE #1156: Graph: Peer dependency conflict
Image

### PR DESCRIPTION
**Pull request by dcblundell**
`vis-data` had a conflicting peer dependency with `vis-network`. I've updated `vis-data` to the latest, major version where they claim there should be no breaking changes for how we're using it. I had to fix a type error after updating, so please check that @aidemsined.

Updated other packages to more recent minor/patch versions at the same time.

Fixes https://github.com/tenstorrent/ttnn-visualizer/issues/1156.

### CODE REVIEW

File: src/components/OperationGraphComponent.tsx [hunk 1]
```diff
@@ -79,8 +79,11 @@ const OperationGraph: React.FC<{
 
     if (currentOperationId !== null && !connectedNodeIds.has(currentOperationId)) {
         const val = connectedNodeIds.values().next().value;
-        focusNodeId = val;
```
Comment (aidemsined) [inline src/components/OperationGraphComponent.tsx]: under which circumstance do you see this happening?

File: src/definitions/PerfTable.ts [hunk 2]
```diff
@@ -62,23 +62,22 @@ export interface PerfTableRow {
     missing?: boolean;
 }
```
Comment (aidemsined) [inline src/definitions/PerfTable.ts]: extaneous chanage?
