### PR TITLE
Highlight current position in congestion heatmap and fixes inaccurate tooltip

### LINKED ISSUE #936: NPE: mark current timestep on heatmap
render current timeline position on timeline

### LINKED ISSUE #938: NPE: inaccurate timestep rendering on heatmap
there is a slight misalignment on tooltip indicating current mouse position

### PR DESCRIPTION
**Pull request by aidemsined**
image

closes #936 
closes #938

### CODE REVIEW

File: src/components/npe/NPEViewComponent.tsx [hunk 1]
```diff
@@ -548,8 +548,9 @@ const NPEView: React.FC<NPEViewProps> = ({ npeData }) => {
                 <NPECongestionHeatMap
                     timestepList={npeData.timestep_data}
                     canvasWidth={canvasWidth}
+                    currentPosition={selectedTimestep}
```
Comment (dcblundell) [inline src/components/npe/NPEViewComponent.tsx]: Wonder if this should be `currentTimestep` because position implies coordinates, but those are calculated within the function.
