### PR TITLE
Make memory zoom options null-safe - prevent blocking error - support for Quasar buffer summary zoom

### LINKED ISSUE #1404: Quasar support: buffer summary broken

### PR DESCRIPTION
**Pull request by aidemsined**
Handle empty chart segments and avoid undefined accesses for zoomed memory options. The segmentedChartData mapping now returns null for empty segments and filters them out. Consume zoomedMemoryOptions with optional chaining and default values (??) for keys, memorySize, plotZoomRange, memoryStart/memoryEnd, and memoryPadding to prevent runtime errors when segments or zoom options are missing.

closes #1404

### CODE REVIEW

File: src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx [hunk 1]
```diff
@@ -81,17 +81,22 @@ function BufferSummaryPlotRendererDRAM({
...
-
-                return {
-                    start: zoomStart,
-                    end: zoomEnd,
-                    padding: (zoomEnd - zoomStart) * MEMORY_ZOOM_PADDING_RATIO,
-                };
-            }),
+            segmentedChartData
+                .map((segment) => {
+                    if (segment.length > 0) {
```
Comment (dcblundell) [inline src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx]: Maybe check that buffers has a length of 2 here because we assume it does when we compute `zoomEnd`.

File: src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx [hunk 2]
```diff
@@ -154,18 +159,21 @@ function BufferSummaryPlotRendererDRAM({
...
                             plotZoomRange={
                                 isZoomedIn
                                     ? [
-                                          zoomedMemoryOptions[index].start - zoomedMemoryOptions[index].padding,
-                                          zoomedMemoryOptions[index].end + zoomedMemoryOptions[index].padding,
+                                          (zoomedMemoryOptions[index]?.start ?? 0) -
+                                              (zoomedMemoryOptions[index]?.padding ?? 0),
+
+                                          (zoomedMemoryOptions[index]?.end ?? MEMORY_SIZE) -
+                                              (zoomedMemoryOptions[index]?.padding ?? 0),
```
Comment (dcblundell) [inline src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx:176]: Looks better to remove padding vs add padding?

**Review by dcblundell — CHANGES_REQUESTED** [review]

File: src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx (hunk 2 above)
Comment (aidemsined) [reply src/components/buffer-summary/BufferSummaryPlotRendererDRAM.tsx:176]: actually the other way around

**Review by dcblundell — APPROVED** [review]
