### PR TITLE
Use device L1 size in L1 small marker

### LINKED ISSUE #1408: Quasar support: incorrect L1 size

### PR DESCRIPTION
**Pull request by aidemsined**
closes #1408 
Add useGetL1Size hook to read worker_l1_size from devices and use it as the fallback/default for useGetL1SmallMarker. Replace hardcoded L1_DEFAULT_MEMORY_SIZE fallbacks with l1Size ?? L1_DEFAULT_MEMORY_SIZE, and include l1Size in the useMemo dependencies to ensure correct recalculation.

### CODE REVIEW

File: src/components/OperationGraphComponent.tsx [hunk 1]
```diff
@@ -80,13 +80,22 @@ const OperationGraph: React.FC<{
...
-        setCurrentOperationId(val);
+    if (currentOperationId !== null && connectedNodeIds.size > 0 && !connectedNodeIds.has(currentOperationId)) {
+        focusNodeId = connectedNodeIds.values().next().value ?? focusNodeId;
     }
 
+    useEffect(() => {
+        if (connectedNodeIds.size === 0) {
+            return;
+        }
+        if (currentOperationId !== null && !connectedNodeIds.has(currentOperationId)) {
```
Comment (dcblundell) [inline src/components/OperationGraphComponent.tsx:91]: Maybe combine these so that we always return early when there are no `connectedNodeIds` or `currentOperationId`.

**Review by dcblundell — APPROVED** [review]
One small suggestion.
