### PR TITLE
Fix/Reset expandable state upon changing reports

### LINKED ISSUE #1272: Scroll restoration: Collapse/Expand state doesn't reset properly when changing reports

### PR DESCRIPTION
**Pull request by dcblundell**
Resets expand state on changing report, and also renames some files/interfaces to better describe their contents.

Closes https://github.com/tenstorrent/ttnn-visualizer/issues/1272.

### CODE REVIEW

File: src/hooks/useRestoreScrollPosition.tsx [hunk 1]
```diff
@@ -57,44 +61,53 @@ const useRestoreScrollPosition = (key?: ScrollLocations) => {
...
+        return listStates?.[key] || null;
+    }, [key, listStates]);
 
     const resetOperationList = useCallback(() => {
         setOperationListFilter('');
         setSelectedDeviceOperations(new Set());
         setShouldSortByID(SortingOptions.ASCENDING);
         setShouldSortDuration(SortingOptions.OFF);
-    }, [setOperationListFilter, setSelectedDeviceOperations, setShouldSortByID, setShouldSortDuration]);
+        setShouldCollapseAllOperations(false);
```
Comment (dcblundell) [inline src/hooks/useRestoreScrollPosition.tsx:80]: This and line 95 are the code changes for the feature.

**Review by aidemsined — APPROVED** [review]
